### ISSUE TITLE
Support reverse flag in build.yaml config

### ISSUE THREAD

**Issue by tomwyr** [netglade/auto_mappr#125]
If I declare multiple dto/domain mappings, where each of them is a two-directional mapping, I'd like to have a single place that lets me generate such code. Right now, there are two ways of achieving that:
- add _dto -> domain_ and _domain -> dto_ entries separately in `AutoMappr` mappers
- set `reverse` flag in each `AutoMappr` mapper

Consider adding `reverse` flag to the build config options so that the behavior can be configured globally:
```yaml
targets:
  $default:
      auto_mappr:
        options:
          reverse: true
```
