### ISSUE TITLE
Can't use freezed generated class as a source 

### ISSUE THREAD

**Issue by wstrange** [netglade/auto_mappr#29]
**Describe the bug**

I have the following mapping:

```dart

@AutoMappr([
  MapType<UserInfo, UserInfoTblCompanion>(constructor: 'insert'),
])
class Mappr extends $Mappr {}
```
I get the build error: "Can't generate mapping UserInfo -> UserInfoTblCompanion as there is non mapped not-nullable required named parameter email"

Of note:

- UserInfoTblCompanion is generated by drift
- UserInfo is generated by freezed, _but is in a different package_ (imported via path: ../client)
- I have tried various shared and non shared builders in build.yaml with no result
- UserInfoTblCompanion does not appear to be the issue as I can map it OK to a test `Foo` class that I created for debugging

Speculation:

Does this have something to do with the freezed class being in a different package? Or the freezed class using a factory constructor:

```dart
class UserInfo with _$UserInfo {
  factory UserInfo(
      {int? id,
      required String email,
      required String loginIdentifier,
      required DateTime updatedAt,
      @Default(0) int primarySectionId}) = _UserInfo;
}
```

**Comment by tenhobi** [comment]
Hi @wstrange, thanks for trying the package and reporting this issue. We will take a look and let you know. :)

**Comment by petrnymsa** [comment]
Hi @wstrange , we currently do not support mapping "freezed-unions" into concrete class. You can however configure mapping of   concrete "freezed subtype" class, e.g. 



```dart
class UserInfoUnion with _$UserInfoUnion {
  factory UserInfo (
      {int? id,
      required String email,
      required String loginIdentifier,
      required DateTime updatedAt,
      @Default(0) int primarySectionId}) = UserInfo;
}

@AutoMappr([
  MapType<UserInfo, UserInfoTblCompanion>(constructor: 'insert'),
])
class Mappr extends $Mappr {}
```

Do not forget to update build.yaml as you need to depend on ".freezed.dart" output

```yaml
targets:
  $default:
    auto_apply_builders: true
    builders:      
      # Mappr - customize its builder
      auto_mappr:
        enabled: false
      :auto_mappr:
        enabled: true

builders:
  auto_mappr:
    required_inputs: [".freezed.dart"] # Depends on Freezed output
    import: "package:auto_mappr/auto_mappr.dart"
    builder_factories: ["autoMapprBuilder"]
    build_extensions: { ".dart": [".auto_mappr.g.part"] }
    auto_apply: none
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
```


---
You can for example manually use "map (maybeMap,..)" from freezed and use AutoMappr for concrete types. 

We've discussed a way to support mapping freezed unions into different classes but we couldn't find a solution how to map different subtypes. Problem is that in top-level freezed union we somehow need to decide which subtype it is, how to map it and cover cases where particular subtype does not match with target class etc. 

Is this solution enough for you? If not, how would you expect this should work?
