### ISSUE TITLE
Is it possible to combine graphql_codegen and auto_mappr?

### ISSUE THREAD

**Issue by denxorz** [netglade/auto_mappr#63]
I am trying to map my graphql classes to my local model, but I keep running into:
```
[SEVERE] auto_mappr on lib/services/graphql/mappr.dart:

dynamic is not a class and cannot be mapped from
package:nurtio/services/graphql/mappr.dart:17:7
   ╷
17 │ class Mappr extends $Mappr {}
   │       ^^^^^
```

If I copy the class from my "services/graphql/queries.graphql.dart" file to the mappr.dart file, it works fine. So expect some ordering issue while generating the files. 

I have tried both `runs_before` and `required_inputs`, but both seem to have no effect. 

My build.yaml
```
targets:
    $default:
        builders:
            graphql_codegen:
                options:
                    clients:
                        - graphql
                        - graphql_flutter
                    scalars:
                        AWSDateTime:
                            type: DateTime
                        JSON:
                            type: Map<String, dynamic>
                    runs_before:
                        - auto_mappr:auto_mappr
            auto_mappr:
                enabled: true
                options:
                    required_inputs:
                        [
                            "services/graphql/queries.graphql.dart",
                            ".freezed.dart",
                            ".drift.dart",
                        ]
```

Is there somebody that knows what I missed? Thanks.

**Comment by tenhobi** [comment]
Hi @denxorz, if it works fine when you copy the code to a non generated file, then it's an issue with the build.

I think you should use just `.graphql.dart` as a required input. And assuming that some `.graphql.dart` file generates (you see it in your project files), it should work.


```yaml
targets:
    $default:
        builders:
            graphql_codegen:
                options:
                    clients:
                        - graphql
                        - graphql_flutter
                    scalars:
                        AWSDateTime:
                            type: DateTime
                        JSON:
                            type: Map<String, dynamic>
                    runs_before:
                        - auto_mappr:auto_mappr
            auto_mappr:
                enabled: true
                options:
                    required_inputs:
                        [
                            ".graphql.dart", # <-- this one
                            ".freezed.dart",
                            ".drift.dart",
                        ]
```

**Comment by denxorz** [comment]
Hello @tenhobi , thanks for the quick answer. 
Changing the required_inputs to ".graphql.dart" still gives the error.

**Comment by denxorz** [comment]
This is the codegen I am using: https://pub.dev/documentation/graphql_codegen/latest/

Created an example:
[mapprgraphql.zip](https://github.com/netglade/auto_mappr/files/11365894/mapprgraphql.zip)

Running `flutter pub run build_runner build` will result in 
```
[SEVERE] auto_mappr:not_shared on lib/services/graphql/mappr.dart:

dynamic is not a class and cannot be mapped from
package:nurtio/services/graphql/mappr.dart:9:7
  ╷
9 │ class Mappr extends $Mappr {}
  │       ^^^^^
```

**Comment by tenhobi** [comment]
@denxorz I would start by adding dependencies in pubspec

```
import 'package:gql/ast.dart';
import 'package:graphql/client.dart' as graphql;
import 'package:graphql_flutter/graphql_flutter.dart' as graphql_flutter;
```

for example these are not in pubspec.

However, the real issue is indeed in setting the builder. We should add some info about builders in Dart to README to make things more clear (we probably removed the info when we added defaults to `freezed` and `json_serializable`). You should disable the default (our) `auto_mappr` builder and enable your builder you create `:auto_mappr_this_project` (note that `:` at the beginning is important, and marks your project).

With this it works 🙏  

```yaml
targets:
    $default:
        builders:
            graphql_codegen:
                options:
                    clients:
                        - graphql
                        - graphql_flutter
            auto_mappr:
                enabled: false
            :auto_mappr_this_project:
                enabled: true

builders:
    auto_mappr_this_project:
        import: "package:auto_mappr/auto_mappr.dart"
        builder_factories: ["autoMapprBuilder"]
        build_extensions: { ".dart": [".auto_mappr.g.part"] }
        auto_apply: dependents
        build_to: cache
        applies_builders: ["source_gen:combining_builder"]
        required_inputs: [".freezed.dart", ".drift.dart", ".graphql.dart"]

```
