### ISSUE TITLE
Class names including $ cause compile error

### ISSUE THREAD

**Issue by denxorz** [netglade/auto_mappr#64]
**Describe the bug**
If you use a class name with a $ sign, it will cause compiler errors in the .g.dart file. It seems the name is directly inserted into a Exception message without escaping.

This might occur with the default setting of the [graphql_codegen](https://pub.dev/documentation/graphql_codegen) package, which generates class names like `Query$character$character`. 
For example: 
```
throw Exception(
          'Mapping Query$character$character → Character failed because Query$character$character was null, and no default value was provided. '
          'Consider setting the whenSourceIsNull parameter on the MapType<Query$character$character, Character> to handle null values during mapping.');
```

**To Reproduce**
Code to reproduce issue: 
1. Add a class with a $ in the mapping annotation
2. Run `flutter pub run build_runner build`

Demo project: [mapprgraphql.zip](https://github.com/netglade/auto_mappr/files/11371076/mapprgraphql.zip)

**Expected behavior**
The class names are espaced before they are merged into strings. 
For example:
```
 throw Exception(
          'Mapping Query\$character\$character → Character failed because Query\$character\$character was null, and no default value was provided. '
          'Consider setting the whenSourceIsNull parameter on the MapType<Query\$character\$character, Character> to handle null values during mapping.');
```

**Version info**
 - Package version : 1.3.1

**Additional context**
As a workaround the `graphql_codegen` can be instructed to change all the class names to something safe, like using the _.
```
targets:
    $default:
        builders:

            graphql_codegen:
                options:
                    clients:
                        - graphql
                        - graphql_flutter
                    namingSeparator: "_" # <------- overwrite the default behavior to a safe char

            auto_mappr:
                enabled: false
            auto_mappr_after_graphql_codegen:
                enabled: true

builders:
    auto_mappr_after_graphql_codegen:
        import: "package:auto_mappr/auto_mappr.dart"
        builder_factories: ["autoMapprBuilder"]
        build_extensions: { ".dart": [".auto_mappr.g.part"] }
        auto_apply: root_package
        build_to: cache
        applies_builders: ["source_gen:combining_builder"]
        required_inputs: [".freezed.dart", ".drift.dart", ".graphql.dart"]
```
